### ISSUE TITLE
Place AppImage on GitHub Releases rather than inside the git repository

### ISSUE THREAD

**Issue by probonopd** [Alex-BusNet/Reveles#1]
Please place the AppImage on GitHub Releases rather than inside the git repository. This way it can be included in the AppImageHub central directory of available AppImages. Thanks.

https://help.github.com/articles/creating-releases/

**Comment by Alex-BusNet** [comment]
No longer using AppImage for releases builds.

**Comment by probonopd** [comment]
That's unfortunate. Why?

**Comment by Alex-BusNet** [comment]
This project is system specific thus the .AppImage file would be useless for anyone without the system. Since this project will be deployed onto a single instance, it is impractical to build the AppImage when the release build can be deployed directly to the system.
